apiVersion: v1
kind: Service
metadata:
  name: mypyapptestdeploypatterns1-service
spec:
  selector:
    app: mypyapptestdeploypatterns1
    env: preprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer