apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
spec:
  selector:
    app: redis-slave
    env: preprod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP