apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
      env: preprod
  template:
    metadata:
      labels:
        app: redis-master
        env: preprod
    spec:
      containers:
        - name: redis-master
          image: k8s.gcr.io/redis:e2e
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
