apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
      env: preprod
  template:
    metadata:
      labels:
        app: redis-slave
        env: preprod
    spec:
      containers:
        - name: redis-slave
          image: gcr.io/google-samples/gb-redisslave:v3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 6379
