apiVersion: v1
kind: Service
metadata:
  name: mypyapptestproxyprobes-service
spec:
  selector:
    app: mypyapptestproxyprobes
    env: preprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer