apiVersion: v1
kind: Service
metadata:
  name: mypyappdeploytest-service
spec:
  selector:
    app: mypyappdeploytest
    env: preprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: LoadBalancer