apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      name: mydeploypod
      labels:
        app: web2
    spec:
      containers:
        - name: nginx2
          image: nginx
          ports:
            - name: web
              containerPort: 80